# Site settings
title: Fairhaven Services
tag_text: FhS
description: Home-based pet care and cleaning
baseurl: "/Fairhaven-Services" # the subpath of your site, e.g. /blog
#url: "https://aduffy70.org" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /Fairhaven-Services/
exclude: ["README.md"]
sass:
  style: compressed
